version: 2

sources:
  - name: homework_db
    loader: S3
    description: "External tables"
    quoting:
      database: false
      schema: false
      identifier: true
    tags:
      - test_db

    tables:
      - name: customer
        description: "Customers source in S3 bucket"
        identifier: src_customer
      - name: lineorder
        identifier: src_lineorder
      - name: part
        identifier: src_part
      - name: supplier
        identifier: src_supplier